### PR TITLE
chore(strapi): upgraded strapi support for v5

### LINKED ISSUE #38: Support on Strapi v5
Updating to Strapi v5 while having this plugin installed resulting this error:

```
✘ [ERROR] Could not resolve "@strapi/design-system/Stack"

    node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:7:22:
      7 │ import { Stack } from "@strapi/design-system/Stack";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./dist/Stack" is forbidden by this package:

    node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/package.json:23:11:
      23 │     "./*": "./dist/*"
         ╵            ~~~~~~~~~~

  The presence of "exports" here makes importing a directory forbidden:

    node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/package.json:9:2:
      9 │   "exports": {
        ╵   ~~~~~~~~~

  Import from "@strapi/design-system/Stack/index.js" to get the file
  "node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/dist/Stack/index.js":

    node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:7:50:
      7 │ import { Stack } from "@strapi/design-system/Stack";
        │                                                   ^
        ╵                                                   /index.js

  You can mark the path "@strapi/design-system/Stack" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@strapi/design-system/Box"

    node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:8:20:
      8 │ import { Box } from "@strapi/design-system/Box";
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./dist/Box" is forbidden by this package:

    node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/package.json:23:11:
      23 │     "./*": "./dist/*"
         ╵            ~~~~~~~~~~

  The presence of "exports" here makes importing a directory forbidden:

    node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/package.json:9:2:
      9 │   "exports": {
        ╵   ~~~~~~~~~

  Import from "@strapi/design-system/Box/index.js" to get the file
  "node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/dist/Box/index.js":

    node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:8:46:
      8 │ import { Box } from "@strapi/design-system/Box";
        │                                               ^
        ╵                                               /index.js

  You can mark the path "@strapi/design-system/Box" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@strapi/design-system/Typography"

    node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:9:27:
      9 │ import { Typography } from "@strapi/design-system/Typography";
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./dist/Typography" is forbidden by this package:

    node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/package.json:23:11:
      23 │     "./*": "./dist/*"
         ╵            ~~~~~~~~~~

  The presence of "exports" here makes importing a directory forbidden:

    node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/package.json:9:2:
      9 │   "exports": {
        ╵   ~~~~~~~~~

  Import from "@strapi/design-system/Typography/index.js" to get the file
  "node_modules/strapi-plugin-wysiwyg-react-md-editor/node_modules/@strapi/design-system/dist/Typography/index.js":

    node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:9:60:
      9 │ import { Typography } from "@strapi/design-system/Typography";
        │                                                             ^
        ╵                                                             /index.js

  You can mark the path "@strapi/design-system/Typography" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.

5:27:14 AM [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:7:22: ERROR: Could not resolve "@strapi/design-system/Stack"
node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:8:20: ERROR: Could not resolve "@strapi/design-system/Box"
node_modules/strapi-plugin-wysiwyg-react-md-editor/admin/src/components/ReactMdEditor/index.tsx:9:27: ERROR: Could not resolve "@strapi/design-system/Typography"
    at failureErrorWithLog (/home/ubuntu/personal/portfolio-lawfirm-strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
    at /home/ubuntu/personal/portfolio-lawfirm-strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
    at /home/ubuntu/personal/portfolio-lawfirm-strapi/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Strapi Version:
v5.0.1

### PR DESCRIPTION
**Pull request by johnmgrant**
* Updated [project structure for v5 support](https://docs.strapi.io/dev-docs/plugins/development/plugin-structure)
* Updated admin interface to utilize new design system and deprecate helper plugin

Closes #38

### CODE REVIEW

**Comment by kwinyyyc** [comment]
@johnmgrant thanks a lot for preparing the PR, I haven't followed along for the strapi upgrade for a while. I have published your changes as a beta version, but the markdown editor doesn't show up, anything I missed there?

**Comment by johnmgrant** [comment]
Hey @kwinyyyc ,

No problem at all. I only completed the path restructuring and resolved the build errors. I'll take a look at it today since I need this for a project I'm working on 😬

**Comment by johnmgrant** [comment]
> @johnmgrant thanks a lot for preparing the PR, I haven't followed along for the strapi upgrade for a while. I have published your changes as a beta version, but the markdown editor doesn't show up, anything I missed there?

Seems to be working for me in Strapi 5.0.2.

Screenshot 2024-10-05 at 9 59 50 AM
Screenshot 2024-10-05 at 10 00 03 AM

Here's my setup:
```json
...
"dependencies": {
    "@strapi/admin": "^5.0.2",
    "@strapi/core": "^5.0.2",
    "@strapi/data-transfer": "^5.0.2",
    "@strapi/design-system": "2.0.0-rc.11",
    "@strapi/icons": "2.0.0-rc.11",
    "@strapi/plugin-users-permissions": "^5.0.2",
    "@strapi/sdk-plugin": "^5.2.6",
    "@strapi/strapi": "^5.0.2",
    "@strapi/typescript-utils": "^5.0.2",
    "@strapi/utils": "^5.0.2",
    "lodash": "^4.17.21",
    "mysql2": "^3.11.3",
    "pm2": "^5.4.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "strapi-plugin-transformer": "git+https://github.com/johnmgrant/strapi-plugin-transformer.git#dev/strapi-v5-migration",
    "strapi-plugin-wysiwyg-react-md-editor": "git+https://github.com/johnmgrant/strapi-plugin-wysiwyg-react-md-editor#dev/strapi-v5-migration",
    "styled-components": "^6.0.0",
    "yup": "^1.4.0"
  }
...
```

**Comment by kwinyyyc** [comment]
@johnmgrant This is the official Markdown editor strapi introduced, you can use it without installing the plugin
Thanks for the information, I will have a look

**Comment by kwinyyyc** [comment]
@johnmgrant FYI your PR is merged and a new version is published https://www.npmjs.com/package/strapi-plugin-wysiwyg-react-md-editor/v/5.0.2 while some features is still broken

**Pull request merged**
